name: pace_tracker_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.4+5

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/person-running.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

