name: pace_tracker_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.1.0+111

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  url_launcher: ^6.0.0-nullsafety.6
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  flutter_launcher_icons: "^0.11.0"
  mockito: ^5.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/person-running.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

