version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0

workflows:
  lint-and-test:
    jobs:
      - flutter/lint:
          version: 2.2.3
      - flutter/unit_test:
          version: 2.2.3
          requires: flutter/lint
