version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0

jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk

workflows:
  lint-and-test:
    jobs:
      - build
      

# VS Code Extension Version: 1.1.1
