version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0

# jobs:
#   lint:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
      
#   test:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
      
#       - store_test_results:
#           path: build/test-results




workflows:
  lint-and-test:
    jobs:
      - flutter/lint:
          version: 2.2.3
      - flutter/test:
          version: 2.2.3
      

# VS Code Extension Version: 1.1.1
