version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0

workflows:
  build:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    name: Build and Test
    steps:
      - checkout
      - flutter/unit_test:
          version: 2.2.3

