// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuABoriMlSpzIpaBxEH-Gfqf39HH3d18',
    appId: '1:98737777551:web:4f0a49d00e7a1b63e879fa',
    messagingSenderId: '98737777551',
    projectId: 'pace-tracker-17d05',
    authDomain: 'pace-tracker-17d05.firebaseapp.com',
    storageBucket: 'pace-tracker-17d05.appspot.com',
    measurementId: 'G-69SKZMWMYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mdj4SPPF1mTd_bDGxHX2s2NLJjPi-PI',
    appId: '1:98737777551:android:31bf949d921cc976e879fa',
    messagingSenderId: '98737777551',
    projectId: 'pace-tracker-17d05',
    storageBucket: 'pace-tracker-17d05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeD6_fyv_-yUBZwqZ1Iob-XiKBmamyhQ0',
    appId: '1:98737777551:ios:1671e2181e24948ae879fa',
    messagingSenderId: '98737777551',
    projectId: 'pace-tracker-17d05',
    storageBucket: 'pace-tracker-17d05.appspot.com',
    iosClientId:
        '98737777551-njjqfi0asnltlcjuqpu721hf1nh46slb.apps.googleusercontent.com',
    iosBundleId: 'manley.dev.pacechecker',
  );
}
