name: Master CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Setup Java environment in order to build the Android app.
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.10'
    
    # Get flutter dependencies.
    - run: flutter pub get

    # Build apk.
    - run: flutter build appbundle

    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v3
      with:
        name: debug-bundle
        path: build/app/outputs/bundle/release/app-release.aab
