name: Pull Request Checks
on:
  pull_request:
    branches:
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Setup Java environment in order to build the Android app.
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        #channel: stable #'beta', 'dev', 'alpha', default to: 'stable'
        flutter-version: '3.3.10' # you can also specify exact version of flutter

    # Get flutter dependencies.
    - run: flutter pub get

    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .

    # Run widget tests for our flutter project.
    - run: flutter test --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
